import { Work_Sans } from "next/font/google";
import "../styles/globals.css";
import { Header } from "@/components/Header";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // you can include the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${workSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
